### ISSUE TITLE
Question about smpl-x motion denoising 

### ISSUE THREAD

**Issue by GrigorySamokhin** [moonbow721/DPoser#1]
Hello! Thanks for your amazing work. Is it possible to apply motion denoising to SMPL-X model (with 71 joints) instead of 21 in your demo? And how good it will work if im going to apply it to in-the-wild animations?

**Comment by moonbow721** [comment]
Hi there!

Thank you so much for your interest in our work, it's great to see your enthusiasm! Regarding your question about the SMPL-X model's 71 joints, let me clarify a bit. The SMPL-X model actually encompasses 54 local poses, including 21 for the body, 30 for the hands, and 3 for the face. In our DPoser demo, we focused on the local body prior, which accounts for the 21 joints you've noticed.

Now, for your intriguing idea about applying DPoser to full-body tasks like motion denoising, it's definitely a path worth exploring! To do this, we'd need to train a model specifically for the whole body, leveraging datasets like SMPL-X in AMASS. It's an exciting prospect, and while we haven't specifically tested motion denoising in wild environments, our experiments with human mesh recovery in such settings have yielded promising results.

I encourage you to experiment with your own data for motion denoising. You can easily do this by adjusting the `file_path` parameter in our demo. Feel free to reach out if you have more questions or exciting updates!

**Comment by GrigorySamokhin** [comment]
I apologize for the late response. Thanks for the detailed answer! I will definitely try
