### ISSUE TITLE
在EHF数据集上得到的结果和主页上的demo不一致

### ISSUE THREAD

**Issue by ShaoYunZhe** [moonbow721/DPoser#3]
作者你好，感谢你的工作！

我在尝试复现你HMR部分的结果，但是似乎效果不尽如人意。我首先使用你提供的demo：`python -m run.demo_fit --img=./examples/image_00077.jpg --openpose=./examples/image_00077_keypoints.json`，看上去没什么问题。
![image](https://github.com/moonbow721/DPoser/assets/88757871/47be57fe-53b9-4d67-97df-2d9c325af06e)
接着，我试图用EHF数据集中的图片和keypoint来替换你提供的例子，但是结果就变得很差。
![image](https://github.com/moonbow721/DPoser/assets/88757871/74f6f76c-85f7-438a-8dbc-2225d01ce3be)
我只修改了python脚本中的文件路径，代码没有任何改动。我想请问这个结果是正常的吗？（我注意到项目主页demo展示了这个图片的定性结果）还是说我没有正确地使用你的代码？

再次表示感谢！！

**Comment by ShaoYunZhe** [comment]
好的，所以说以您现在公开的代码为准，得到上图中的结果是正常的，并不是我的使用方法不对。是这样吗？

**Comment by moonbow721** [comment]
是的，如果想要改善这个情况，也可以尝试调整优化的参数，例如增大pose_prior_weight。

**Comment by ShaoYunZhe** [comment]
好的，那这样看起来，一个准确的关键点检测器很重要。感谢您的回复！
