### ISSUE TITLE
Thank you for your work !  I want to ask which SMPL-X model do you use? V1.1 or  with removed head bun? 

### ISSUE THREAD

**Issue by ouusan** [moonbow721/DPoser#4]
Hello, thank you for your great work!!!
 I have two questions:
Which SMPL-X model do you use and 
where can i find your requirements.txt file? since i have an Error that no such file while running pip install -r requirements.txt 
Thankyou!

**Comment by moonbow721** [comment]
Hello!

Thank you for your kind words and for bringing this to our attention!

We are using the SMPL-X v1.1 model, which you can download from here: [SMPL-X v1.1](https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=models_smplx_v1_1.zip).

Regarding the requirements.txt file, we apologize for the oversight. It has now been uploaded to our repository. Please try downloading it again to resolve the installation error.

Thank you for your patience and support!
